
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tododb
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"

#  backend:
#    build: ./backend
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/tododb
#    networks:
#      - appnet

#  frontend:
#    build: ./frontend
#    depends_on:
#      - backend
#    ports:
#      - "3000:3000"
#    networks:
#      - appnet

volumes:
  dbdata:

#networks:
#  appnet:
